### ISSUE TITLE
weewx stops with error "too many values to unpack"

### ISSUE THREAD

**Issue by sheldon-andrea** [matthewwall/weewx-wxt5x0#4]
Hi there,
I was trying the weewx-wxt5x0 driver with my Vaisala WXT-510. 
At the beginning, it seemed to work perfectly. But after a couple of hours working, it gives the error "ValueError: too many values to unpack" and exits. I need just to give a "service weewx restart" to make it start again, but after some time it falls into this error again.
Do you know how I can fix this?

```
Nov 28 15:27:47 raspberrypi-ingv weewx[3424]: wxt5x0: parsed: {'temperature': 27.9, 'heating_voltage': 0.0, 'rain': 0.0, 'humidity': 39.4, 'pressure': 1003.2, 'heating_temperature': 28.1, 'wind_dir_avg': 51.0, 'wind_speed_avg': 0.1}
Nov 28 15:27:47 raspberrypi-ingv weewx[3424]: wxt5x0: mapped: {'heatingVoltage': 0.0, 'dateTime': 1574951268, 'pressure': 1003.2, 'outHumidity': 39.4, 'rain': 0.0, 'heatingTemp': 28.1, 'windDir': 51.0, 'outTemp': 27.9, 'windSpeed': 0.1, 'rain_total': 0.0, 'usUnits': 17}
Nov 28 15:27:48 raspberrypi-ingv weewx[3424]: wxt5x0: raw: 30 52 30 2C 44 6D 3D 30 35 31 44 2C 53 6D 3D 30 2E 31 4D 2C 54 61 3D 32 37 2E 39 43 2C 55 61 3D 33 39 2E 34 50 2C 50 61 3D 31 30 30 33 2E 32 48 2C 52 63 3D 30 2E 30 30 4D 2C 54 68 3D 32 38 2E 31 43 2C 56 68 3D 30 2E 30 4E 0D 0A
Nov 28 15:27:48 raspberrypi-ingv weewx[3424]: wxt5x0: parsed: {'temperature': 27.9, 'heating_voltage': 0.0, 'rain': 0.0, 'humidity': 39.4, 'pressure': 1003.2, 'heating_temperature': 28.1, 'wind_dir_avg': 51.0, 'wind_speed_avg': 0.1}
Nov 28 15:27:48 raspberrypi-ingv weewx[3424]: wxt5x0: mapped: {'heatingVoltage': 0.0, 'dateTime': 1574951269, 'pressure': 1003.2, 'outHumidity': 39.4, 'rain': 0.0, 'heatingTemp': 28.1, 'windDir': 51.0, 'outTemp': 27.9, 'windSpeed': 0.1, 'rain_total': 0.0, 'usUnits': 17}
Nov 28 15:27:49 raspberrypi-ingv weewx[3424]: wxt5x0: raw: 30 52 30 2C 44 6D 3D 30 35 31 44 2C 53 6D 3D 30 2E 31 4D 2C 54 61 3D 32 37 2E 39 43 2C 55 61 3D 33 39 2E 34 50 2C 50 61 3D 31 30 30 33 2E 32 48 2C 52 63 3D 30 2E 30 30 4D 2C 54 68 3D 32 38 2E 31 43 2C 56 68 3D 30 2E 30 4E 0D 0A
Nov 28 15:27:49 raspberrypi-ingv weewx[3424]: wxt5x0: parsed: {'temperature': 27.9, 'heating_voltage': 0.0, 'rain': 0.0, 'humidity': 39.4, 'pressure': 1003.2, 'heating_temperature': 28.1, 'wind_dir_avg': 51.0, 'wind_speed_avg': 0.1}
Nov 28 15:27:49 raspberrypi-ingv weewx[3424]: wxt5x0: mapped: {'heatingVoltage': 0.0, 'dateTime': 1574951270, 'pressure': 1003.2, 'outHumidity': 39.4, 'rain': 0.0, 'heatingTemp': 28.1, 'windDir': 51.0, 'outTemp': 27.9, 'windSpeed': 0.1, 'rain_total': 0.0, 'usUnits': 17}
Nov 28 15:27:50 raspberrypi-ingv weewx[3424]: wxt5x0: raw: 30 52 31 2C 44 6E 3D 30 6D 3D 30 33 32 44 2C 53 6D 3D 30 2E 31 4D 2C 54 61 3D 32 37 2E 39 43 2C 55 61 3D 33 39 2E 34 50 2C 50 61 3D 31 30 30 33 2E 32 48 2C 52 63 3D 30 2E 30 30 4D 2C 54 68 3D 32 38 2E 33 43 2C 56 68 3D 30 2E 30 4E 0D 0A
Nov 28 15:27:50 raspberrypi-ingv weewx[3424]: engine: Main loop exiting. Shutting engine down.
Nov 28 15:27:50 raspberrypi-ingv weewx[3424]: engine: Shutting down StdReport thread
Nov 28 15:27:50 raspberrypi-ingv weewx[3424]: engine: StdReport thread has been terminated
Nov 28 15:27:50 raspberrypi-ingv weewx[3424]: wxt5x0: close serial port /dev/ttyUSB0
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]: engine: Caught unrecoverable exception in engine:
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****  too many values to unpack
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****  Traceback (most recent call last):
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****    File "/home/weewx/bin/weewx/engine.py", line 877, in main
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****      engine.run()
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****    File "/home/weewx/bin/weewx/engine.py", line 188, in run
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****      for packet in self.console.genLoopPackets():
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****    File "/home/weewx/bin/user/wxt5x0.py", line 452, in genLoopPackets
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****      data = Station.parse(raw)
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****    File "/home/weewx/bin/user/wxt5x0.py", line 232, in parse
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****      abbr, vstr = part.split('=')
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****  ValueError: too many values to unpack
Nov 28 15:27:51 raspberrypi-ingv weewx[3424]:     ****  Exiting.
```

Thank you,
Andrea

**Comment by matthewwall** [comment]
looks like you are getting some odd data in the response:
```
>>> x = "30 52 31 2C 44 6E 3D 30 6D 3D 30 33 32 44 2C 53 6D 3D 30 2E 31 4D 2C 54 61 3D 32 37 2E 39 43 2C 55 61 3D 33 39 2E 34 50 2C 50 61 3D 31 30 30 33 2E 32 48 2C 52 63 3D 30 2E 30 30 4D 2C 54 68 3D 32 38 2E 33 43 2C 56 68 3D 30 2E 30 4E 0D 0A"
>>> ''.join([chr(int(y,16)) for y in x.split(' ')])
'0R1,Dn=0m=032D,Sm=0.1M,Ta=27.9C,Ua=39.4P,Pa=1003.2H,Rc=0.00M,Th=28.3C,Vh=0.0N\r\n'
>>> z = ''.join([chr(int(y,16)) for y in x.split(' ')])
>>> z.strip()
'0R1,Dn=0m=032D,Sm=0.1M,Ta=27.9C,Ua=39.4P,Pa=1003.2H,Rc=0.00M,Th=28.3C,Vh=0.0N'
>>> z.strip().split(',')
['0R1', 'Dn=0m=032D', 'Sm=0.1M', 'Ta=27.9C', 'Ua=39.4P', 'Pa=1003.2H', 'Rc=0.00M', 'Th=28.3C', 'Vh=0.0N']
>>> for q in z.strip().split(','):
...     if '=' in q:
...             q.split('=')
... 
['Dn', '0m', '032D']
['Sm', '0.1M']
['Ta', '27.9C']
['Ua', '39.4P']
['Pa', '1003.2H']
['Rc', '0.00M']
['Th', '28.3C']
['Vh', '0.0N']
```
the field `Dn=0m=032D` is messed up - it looks like the value for `Dn` was somehow lost.

i will make the driver ignore those packets.

**Comment by sheldon-andrea** [comment]
Thank you! will you upload a new version?

**Comment by matthewwall** [comment]
please try the latest (commit 8434bf3)
